

################### apollo 配置 start###############
## 指定app_id
#app.id=fctms_2.1.0-20200717100814
## 指定连接路由地址
#apollo.meta=http://127.0.0.1:8704
## 指定集群
#apollo.cluster=
## 缓存路径
apollo.cacheDir=E:\\test\\apollo\\config

## springboot 集成方式
apollo.bootstrap.enabled = true
apollo.bootstrap.namespaces = values.yaml
################### apollo 配置 end###############

