### 指定app_id
#app.id=test.app6
### 指定连接路由地址
#apollo.meta=http://192.168.175.128:8080
### 指定集群
#apollo.cluster=cluster1
### 缓存路径
#apollo.cacheDir=E:\\test\\apollo\\config
#
### springboot 集成方式
#apollo.bootstrap.enabled = true
#apollo.bootstrap.namespaces = application,application.yml

## 指定app_id
app.id=aitask_1.4.2-20200629172857
## 指定连接路由地址
apollo.meta=http://10.33.43.13:36094/
## 指定集群
apollo.cluster=
## 缓存路径
apollo.cacheDir=E:\\test\\apollo\\config

## springboot 集成方式
apollo.bootstrap.enabled = true
apollo.bootstrap.namespaces = values.yaml,values.properties